# Generated by Django 4.2.4 on 2023-09-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.cita'),
        ),
    ]
