# Generated by Django 4.2.4 on 2023-10-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='imagen_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
